#!/bin/sh
scope="public/javascripts/* routes/* tests/";
eslint -f pretty $scope

if [ $? -eq 0 ]; then
    echo No Eslint error, ready to push!
    #exiting statement
else
    echo Eslint Finished, Errors detected, trying to fix...
    if [ $? -eq 0 ]; then
        echo Error has been fixed, ready to push!
        #exiting statement
        else
        echo Eslint force fix failed, please try manually fix above problem
        exit 1
    fi
    eslint -f pretty --fix $scope
fi
echo "Eslint finished, type \"make push\" to automatically push repo."



